services:
  - type: web
    name: sistema-recomendacao-medica
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sistema_recomendacao:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
